# M-Pesa + SMS placeholders â€” replace with real values before using in production

mpesa:
  env: sandbox
  payment-type: PAYBILL   # PAYBILL | TILL
  consumer-key: gLKj2u28W7o6EncnK97GyyWtQ2S0HfyMGFfdDJlaMutu4sbl
  consumer-secret: bGP6Fqjn8v8cNQEILhwYGhuWqRSrqiBswNwcXS3A0Kc0zBSxGfONt6JDp7JnQzTH
  shortcode: 174379
  passkey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
  stk:
    callback-url: https://thumbless-melva-tinselly.ngrok-free.dev/api/payments/mpesa/stk/callback


#mpesa:
#  env: production
#  consumer-key: xxxxxxxxx
#  consumer-secret: xxxxxxxxx
#  shortcode: 123456
#  passkey: xxxxxxxxx
#  stk:
#    callback-url: https://client-domain.com/api/payments/mpesa/stk/callback
#  c2b:
#    confirm-url: https://client-domain.com/api/payments/mpesa/c2b/confirm
#    validate-url: https://client-domain.com/api/payments/mpesa/c2b/validate
#  payment-type: PAYBILL # PAYBILL | TILL

sms:
  env: sandbox
  consumer-key: YOUR_SMS_CONSUMER_KEY
  consumer-secret: YOUR_SMS_CONSUMER_SECRET
  # For customer SMS (Daraja-like), base-url depends on environment:
  base-url-sandbox: https://sandbox.safaricom.co.ke
  base-url-production: https://api.safaricom.co.ke
  shortcode: 12345     # if required
  sender-name: "MyBusiness"
  default-country-code: "+254"